#%RAML 1.0 NamedExample
title: object1

phone:  '319-363-6762'
fax: '319-363-8992'
search_type: 'A'
search_no: 3000074100
agent_no: 151134
wsresult: 100
wsmessage: 'SUCCESSFUL'
contact_name: "CHERRYL BARTUNEK"
account_number: "3000074110"
account_address: "2709 PRIMROSE LN SW"
account_state: "IA"
account_zip: "52404-2453"
service_center: true