#%RAML 1.0
version: v1
title: Sentiment Analysis Data Service

traits: 
  queryParameters : !include traits/queryparameters-trait.raml
  hasResponseItem :  !include traits/Response200-trait.raml

uses:
  library2: datatypes/response-library.raml

resourceTypes: 
  item:
    usage: use this resourceType to represent any single item
    description: a single <<typename>> collection
    get:
     is: [queryParameters]
     responses:
      200:
       description: valid response data
       body:
        application/json:
         type: library2.getdata
         example: !include examples/getresponse-example.raml
         
      400:
       description: error response
       body:
        application/json:
         type: library2.Message
         example: !include examples/badresponse-example.raml
    
    post:
     responses:
      201:
       body:
        application/json:
         type: library2.getdata
         example: !include examples/getresponse-example.raml
       
      401:
       body:
        application/json:
         type: library2.Message
         example: !include examples/badresponse-example.raml
         
/wsact:
   type:  { item : {typename : "wsact"} }
   
/wzat:
   type:  { item : {typename: "wzat"} }
      
       