
#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/a20f71fd-b2d3-4c8c-abc8-052d786d2148 # baseUri: https://mocksvc.mulesoft.com/mocks/fd2bd5e1-d4b9-4749-a839-0f5e00a34949 # 
title: New API for retrive wsact by agent information
version: '1.0'
protocols:
  - HTTP
uses: 
  library2: data_types/library1.raml
traits: 
   hasResponseItem :  !include traits/hasResponseItem.raml
   queryParameters : !include traits/query_parameters_search_type.raml

resourceTypes: 
 item:
    usage: use this resourceType to represent any single item
    description: a single <<typename>> collection
    get:
     
     is: [queryParameters]
     responses: 
      200:
       description: valid response data
       body: 
        application/json:
         type: library2.getdata
         example: !include examples/get_response.raml
      400:
       description: error response
       body: 
         application/json:
           type: library2.Message
           example: !include examples/example_bad_response.raml
    post:
    
     
     responses: 
       201:
        body: 
         application/json:
          type: library2.getdata
          example: !include examples/get_response.raml

       401:
        body: 
          application/json:
            type: library2.Message
            example: !include examples/example_bad_response.raml





/wsact:
   type:  { item : {typename : "wsact"} }

/wzat:
   type:  { item : {typename: "wzat"}}

     
    



