#%RAML 1.0 DataType

description: message


properties:
  message: 
    description: text of the message
    type: string
    example: 'success'
  code?:
    description: id
    type: string
    example: '200'
  