#%RAML 1.0 DataType

 
 properties: 
   phone:
    type: string
   fax:
    type: string
   search_type:
    type: string
   search_no:
    type: integer
   agent_no:
    type: integer
   wsresult:
    type: integer
   wsmessage:
    type: string
   contact_name:
    type: string
   account_number:
    type: integer
   account_address:
    type: string
   account_state:
    type: string
   account_zip:
    type: string
   service_center:
    type: boolean

   lineItems:
    type: array
    items: !include listitems.raml

   statusmessages:
    properties:
     StatusMessage:
      type: string
   




     
